# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961196))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961222))),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeRanges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961196))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961222))),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_manager.Appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961196))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961222))),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=200, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('appointments', models.ManyToManyField(to='appointments_manager.Appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961196))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 7, 961222))),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_manager.Appointment')),
                ('time_ranges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_manager.TimeRanges')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
