# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76853)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76877)),
        ),
        migrations.AlterField(
            model_name='timeranges',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76853)),
        ),
        migrations.AlterField(
            model_name='timeranges',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76877)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76853)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76877)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76853)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 34, 13, 76877)),
        ),
    ]
