# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230692)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230719)),
        ),
        migrations.AlterField(
            model_name='timeranges',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230692)),
        ),
        migrations.AlterField(
            model_name='timeranges',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230719)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230692)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230719)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230692)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 8, 58, 10, 230719)),
        ),
    ]
